version: 0.2

env:
  variables:
    LAMBDA_NAME: "cmg-consumersystems-arc-video-center-ingest"

phases:
  install:
    commands:
      - yarn install --production
    runtime-versions:
      nodejs: 20
  pre_build:
    commands:
      - mkdir deploy
      - cp index.js deploy
      - cp -r node_modules deploy/
      - cp -r lib deploy/
      - cp -r resources deploy/
      - cd deploy
      - zip -r ../deploy.zip .
      - cd ..
  build:
    commands:
      - aws lambda update-function-code --function-name $LAMBDA_NAME-${STAGE} --zip-file fileb://deploy.zip --publish
      - sleep 30
      - aws lambda update-function-configuration --function-name $LAMBDA_NAME-${STAGE} --runtime nodejs20.x --handler index.handler --region us-east-1
