version: 0.2

env:
  variables:
    LAMBDA_NAME: "arc-video-center-ingest-dev"
    # BUCKET_NAME: "cmg-digidev-radioalexa-lambda-code-bucket"
  parameter-store:
    GITHUB_TOKEN: "/platform-api/bot/GITHUB_TOKEN" # GitHub API
    SSH_KEY: "/platform-api/bot/SSH_KEY" # NPM install private GitHub repos
    
phases:
  install:
    commands:
      # - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 --storage-driver=overlay&
      # - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"
      - yarn install --production
    runtime-versions:
      nodejs: 10
  pre_build:
    commands:
      # Seems to be a bug with serverless 1.52.0
      - mkdir deploy
      - cp index.js deploy
      - cp -r node_modules deploy/
      - cp -r lib deploy/
      - cp -r resources deploy/
      - cd deploy
      - zip -r ../deploy.zip .
  build:
    commands:
      - aws lambda update-function-code --function-name $LAMBDA_NAME --zip-file fileb:///deploy.zip --publish